name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate github-contribution-grid-snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#41a1f4&color_dots=#161b22,#1a1b26,#2f3549,#41a1f4,#70b0ff
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#7c3aed&color_dots=#1a1b26,#2f3549,#4a5270,#7c3aed,#a78bfa
          
      - name: Deploy to output branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: output
          token: ${{ secrets.GITHUB_TOKEN }}
